version: '3'
services:
  bend:
    image: bend
    build: 
      context: ./bend
      dockerfile: ./Dockerfile
    ports: 
      - 9000:9000
    networks: 
      - net
  fend:
    image: fend
    env_file:
      - ./fend/src/web_vars.env
    build:
      context: ./fend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks: 
      - net

networks: 
    net: